[package]
name = "coppice-config"
version = "0.1.0"
edition = "2021"

[dependencies]
directories = "5"
figment = { version = "0.10", features = ["toml", "env"] }
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
coppice-connectors = { path = "../connectors" }
tempfile = "3"
toml = "0.8"
